import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ["'DM Serif Display'", "serif"],
        heading: ["'Bricolage Grotesque'", "sans-serif"],
        body: ["'Plus Jakarta Sans'", "sans-serif"],
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        mono: ["'Geist Mono'", "monospace"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Clypt index.css tokens → utilities (e.g. text-text-muted, bg-surface-1).
        // Note: `border` stays hsl(var(--border)) above for shadcn; use border-clypt-border for --color-border.
        "clypt-bg": "var(--color-bg)",
        "surface-1": "var(--color-surface-1)",
        "surface-2": "var(--color-surface-2)",
        "surface-3": "var(--color-surface-3)",
        "border-subtle": "var(--color-border-subtle)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        violet: "var(--color-violet)",
        "violet-dim": "var(--color-violet-dim)",
        "violet-muted": "var(--color-violet-muted)",
        amber: "var(--color-amber)",
        "amber-muted": "var(--color-amber-muted)",
        cyan: "var(--color-cyan)",
        "cyan-muted": "var(--color-cyan-muted)",
        green: "var(--color-green)",
        "green-muted": "var(--color-green-muted)",
        rose: "var(--color-rose)",
        "rose-muted": "var(--color-rose-muted)",
        // Custom Clypt palette (prefixed utilities)
        "clypt-surface-1": "var(--color-surface-1)",
        "clypt-surface-2": "var(--color-surface-2)",
        "clypt-surface-3": "var(--color-surface-3)",
        "clypt-border": "var(--color-border)",
        "clypt-border-subtle": "var(--color-border-subtle)",
        "clypt-text-primary": "var(--color-text-primary)",
        "clypt-text-secondary": "var(--color-text-secondary)",
        "clypt-text-muted": "var(--color-text-muted)",
        "clypt-violet": "var(--color-violet)",
        "clypt-violet-dim": "var(--color-violet-dim)",
        "clypt-violet-muted": "var(--color-violet-muted)",
        "clypt-amber": "var(--color-amber)",
        "clypt-amber-muted": "var(--color-amber-muted)",
        "clypt-cyan": "var(--color-cyan)",
        "clypt-cyan-muted": "var(--color-cyan-muted)",
        "clypt-green": "var(--color-green)",
        "clypt-green-muted": "var(--color-green-muted)",
        "clypt-rose": "var(--color-rose)",
        "clypt-rose-muted": "var(--color-rose-muted)",
        "clypt-trend": "var(--color-trend)",
        "clypt-trend-muted": "var(--color-trend-muted)",
        "clypt-comment": "var(--color-comment)",
        "clypt-comment-muted": "var(--color-comment-muted)",
        "clypt-retention": "var(--color-retention)",
        "clypt-retention-muted": "var(--color-retention-muted)",
        // Node type colors
        "node-claim": "var(--node-claim)",
        "node-explanation": "var(--node-explanation)",
        "node-example": "var(--node-example)",
        "node-anecdote": "var(--node-anecdote)",
        "node-reaction-beat": "var(--node-reaction-beat)",
        "node-qa-exchange": "var(--node-qa-exchange)",
        "node-challenge-exchange": "var(--node-challenge-exchange)",
        "node-setup-payoff": "var(--node-setup-payoff)",
        "node-reveal": "var(--node-reveal)",
        "node-transition": "var(--node-transition)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0", opacity: "0" },
          to: { height: "var(--radix-accordion-content-height)", opacity: "1" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)", opacity: "1" },
          to: { height: "0", opacity: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-out": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(10px)" },
        },
        "scale-in": {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "waveform-drift-1": {
          "0%, 100%": { transform: "translateY(-50%) translateY(-8px)" },
          "50%": { transform: "translateY(-50%) translateY(8px)" },
        },
        "waveform-drift-2": {
          "0%, 100%": { transform: "translateY(-50%) translateY(6px)" },
          "50%": { transform: "translateY(-50%) translateY(-6px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-out": "fade-out 0.3s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "waveform-drift-1": "waveform-drift-1 6s ease-in-out infinite alternate",
        "waveform-drift-2": "waveform-drift-2 6s ease-in-out infinite alternate",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
